export default {
  locale: 'en',
  Header: {
    TITLE: 'Fortnine 2 : Shifumi',
    CREATE: 'Create Account',
    DISCONNECT: 'Disconnect here',
  },
  LoginForm: {
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CREATE: 'Create your account',
    ERROR: 'Bad Username or Password please retry',
  },
  CreateAccount: {
    INFOPWD: 'Your password must contain at least 8 characters and one uppercase character',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    LOGIN: 'You already have an account login',
    C_PASSWORD: 'Confirm password',
    EMAIL: 'Email',
    ERROR: 'This account already exist',
    ERROR_PM: "Passwords doesn't match",
  },
  Lobby: {
    TABNAMEROOM: 'Name Room',
    TABOWNER: 'Owner',
    TABCURCONNECT: 'Currently connected',
    TABOPTIONS: 'Options',
    NOROOM: 'No room available',
  },
  CreateRoom: {
    NAME: 'Name',
    SERVER: 'The connection with our server is not established yet please wait',
    EMPTY: 'Please choose a name for the room',
  },
  Room: {
    FULL: 'The room you chose is already full',
    BUSY: 'You are currently inside a room leave it before joining another room',
  },
  CustomDialog: {
    OOPS: 'We got a problem...',
    FULL: 'The room you chose is already full',
    EMPTY: 'Please choose a name for the room',
    BUSY: 'You are currently inside a room leave it before joining another room',
    SERVER: 'The connection with our server is not established yet please wait',
    OK: 'OK',
  },
  CustomButton: {
    LOGIN: 'Login',
    ADDROOM: 'Add a new room',
    JOIN: 'Join',
    CREATE: 'Create your account',
    CREATEROOM: 'Create a new room',
    ROCK: 'Rock',
    PAPER: 'Paper',
    SCISSORS: 'Scissors',
    DISCONNECTROOM: 'Quit game room',
  },
  GameRoom: {
    CHOOSE: 'Choose your move tou have: ',
    WAITING: 'Waiting for an opponent',
    OPPONENTMOVE: 'Your oppenent played: ',
    OPPPONENTPLAYED: 'Your is waiting for you',
    WAITOPPONENT: 'Waiting for your opponent play',
    VICTORY: '#1 VICTORY ROYALE',
    DEFEAT: 'You loose better luck next time',
    DRAW: 'DRAW! No winner',
    ROCK: 'Rock',
    PAPER: 'Paper',
    SCISSORS: 'Scissors',
    WON: 'You won the previous round',
    LOST: 'You lost the previous round',
    TIE: 'No winner on the previous it\'s a draw',
    SCORE: 'The current score is: ',
    FINALSCORE: 'The final score is: ',
  },
};
