export default {
  locale: 'en',
  Header: {
    TITLE: 'Fortnine 2 : Shifumi',
    CREATE: 'Create Account',
    DISCONNECT: 'Disconnect here',
  },
  LoginForm: {
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CREATE: 'Create your account',
    ERROR: 'Bad Username or Password please retry',
  },
  CreateAccount: {
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CREATE: 'Create your account',
    LOGIN: 'You already have an account login',
    C_PASSWORD: 'Confirm password',
    EMAIL: 'Email',
    ERROR: 'This account already exist',
    ERROR_PM: "Passwords doesn't match",
  },
  Lobby: {
    TABNAMEROOM: 'Name Room',
    TABOWNER: 'Owner',
    TABCURCONNECT: 'Currently connected',
    TABOPTIONS: 'Options',
    NOROOM: 'No room available',
    ADDROOM: 'Add a new room',
  },
  CreateRoom: {
    NAME: 'Name',
    CREATEROOM: 'Create a new room',
    SERVER: 'The connection with our server is not established yet please wait',
    EMPTY: 'Please choose a name for the room',
    OOPS: 'We got a problem...',
    OK: 'OK',
  },
  Room: {
    OOPS: 'We got a problem...',
    JOIN: 'Join',
    FULL: 'The room you chose is already full',
    BUSY: 'You are currently inside a room leave it before joining another room',
    SERVER: 'The connection with our server is not established yet please wait',
    OK: 'OK',
  },
};
